version: '3.4'

services:

  andrewgblissdb:
    image: postgres:12.7
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - andrewgblissdb_postgres:/var/lib/postgresql/data

volumes:
  andrewgblissdb_postgres:
